[[protocols]]
name = "rav494"
protocol = "nec"
[protocols.scancodes]
0x7f015a = "KEY_NUMERIC_0"
0x7f0151 = "KEY_NUMERIC_1"
0x7f0152 = "KEY_NUMERIC_2"
0x7f0153 = "KEY_NUMERIC_3"
0x7f0154 = "KEY_NUMERIC_4"
0x7f0155 = "KEY_NUMERIC_5"
0x7f0156 = "KEY_NUMERIC_6"
0x7f0157 = "KEY_NUMERIC_7"
0x7f0158 = "KEY_NUMERIC_8"
0x7f0159 = "KEY_NUMERIC_9"
0x7f015b = "KEY_10CHANNELSUP"
0x7070f = "KEY_MUTE"
0x7a1c = "KEY_MUTE"
0x7070b = "KEY_VOLUMEDOWN"
0x70707 = "KEY_VOLUMEUP"
0x70710 = "KEY_CHANNELDOWN"
0x70712 = "KEY_CHANNELUP"
0x70702 = "KEY_POWER"
0x7f0166 = "KEY_MODE"
0x7f0168 = "KEY_PLAY"
0x7f0167 = "KEY_PAUSE"
0x7f0169 = "KEY_STOP"
0x7f016a = "KEY_REWIND"
0x7f016b = "KEY_FORWARD"
0x7f016c = "KEY_PREVIOUS"
0x7f016d = "KEY_NEXT"
0x857adfa0 = "KEY_HOME"
0x857adba4 = "KEY_MENU"
0x7aaa = "KEY_BACK"
0x7f0160 = "KEY_INFO"
0x7a9d = "KEY_UP"
0x7a9c = "KEY_DOWN"
0x7a9f = "KEY_LEFT"
0x7a9e = "KEY_RIGHT"
0x7ade = "KEY_OK"
0x7a84 = "KEY_SETUP"
0x857a146b = "KEY_OPTION"
0x857a1768 = "KEY_NUMERIC_STAR"
0x857a5827 = "KEY_INFO"
0x857a3847 = "KEY_1"
0x857a354a = "KEY_F2"
0x857a324d = "KEY_3"
0x857a2f50 = "KEY_4"
0x70701 = "KEY_F11"
0x7f015c = "KEY_COMPOSE"
0x7a1a = "KEY_PAGEUP"
0x7a1b = "KEY_PAGEDOWN"
0x857a7c03 = "KEY_RED"
0x7f0150 = "KEY_POWER2"

